<?php

declare(strict_types=1);

namespace HomeSide\AiAgents\Models;

use HomeSide\AiAgents\Contracts\AuthorizesProposalDecisions;
use HomeSide\AiAgents\Events\ActionProposalAccepted;
use HomeSide\AiAgents\Events\ActionProposalCreated;
use HomeSide\AiAgents\Events\ActionProposalExecuted;
use HomeSide\AiAgents\Events\ActionProposalExpired;
use HomeSide\AiAgents\Events\ActionProposalFailed;
use HomeSide\AiAgents\Events\ActionProposalRejected;
use HomeSide\AiAgents\Models\Concerns\ValidatesOnWrite;
use HomeSide\AiAgents\Tenancy\BelongsToTenant;
use Illuminate\Contracts\Validation\Validator as ValidatorContract;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

/**
 * A proposed action generated by an agent that awaits user acceptance.
 *
 * Human-in-the-loop pattern: agents never mutate host data directly. A tool
 * (typically built from stubs/ActionProposalTool.php.stub) creates a pending
 * proposal; the user accepts or rejects it through the host's own action,
 * which dispatches to domain handlers. The package standardises persistence,
 * validation, lifecycle and querying — executing the proposed action always
 * remains host-side because proposal types and handlers are domain-specific.
 *
 * @property string $id UUID primary key.
 * @property int|string $user_id The id of the user who received the proposal.
 * @property int|string|null $household_id The tenant id (column name configurable), if any.
 * @property string|null $conversation_id The id of the conversation that produced the proposal, if any.
 * @property string $type Host-defined proposal type (e.g. 'add_shopping_items').
 * @property array<string, mixed> $payload The action payload.
 * @property string|null $reason Human-readable explanation shown to the user.
 * @property string $status pending|accepted|rejected|expired|executing|executed|failed.
 * @property Carbon|null $expires_at When the proposal expires, if any.
 * @property int|string|null $decided_by The id of the user who decided, if any.
 * @property Carbon|null $decided_at When the decision was made.
 * @property string|null $decision_note Additional context about the decision.
 * @property array<string, mixed>|null $original_payload The payload at creation time (when amended).
 * @property string|null $source_type The morph type of the originating entity.
 * @property int|string|null $source_id The morph id of the originating entity.
 * @property string|null $ai_run_id The AI run that generated this proposal.
 * @property Carbon|null $executed_at When the action finished executing.
 * @property array<string, mixed>|null $execution_result The serialisable execution result.
 * @property string|null $execution_error Error message when execution failed.
 * @property Carbon|null $created_at The timestamp when the proposal was created.
 * @property Carbon|null $updated_at The timestamp when the proposal was last updated.
 *
 * Relationships:
 * @property Model|null $user The user who received the proposal (resolved via config).
 * @property AiConversation|null $conversation The conversation that produced the proposal.
 * @property Model|null $source The originating entity (morph).
 * @property AiRun|null $aiRun The AI run that generated this proposal.
 */
class AiActionProposal extends Model
{
    use BelongsToTenant, HasUuids, ValidatesOnWrite;

    public const STATUS_PENDING = 'pending';

    public const STATUS_ACCEPTED = 'accepted';

    public const STATUS_REJECTED = 'rejected';

    public const STATUS_EXPIRED = 'expired';

    public const STATUS_EXECUTING = 'executing';

    public const STATUS_EXECUTED = 'executed';

    public const STATUS_FAILED = 'failed';

    protected $fillable = [
        'user_id',
        'conversation_id',
        'type',
        'payload',
        'reason',
        'status',
        'expires_at',
        'decided_by',
        'decided_at',
        'decision_note',
        'original_payload',
        'source_type',
        'source_id',
        'ai_run_id',
        'executed_at',
        'execution_result',
        'execution_error',
    ];

    /**
     * Get the attribute casts for the model.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'payload' => 'array',
            'expires_at' => 'datetime',
            'decided_at' => 'datetime',
            'executed_at' => 'datetime',
            'original_payload' => 'array',
            'execution_result' => 'array',
        ];
    }

    /**
     * Validation rules for validated writes.
     *
     * @return array<string, mixed>
     */
    protected static function rules(): array
    {
        return [
            'user_id' => ['required'],
            'conversation_id' => ['nullable', 'string', 'max:64'],
            // Host-defined types: lowercase slug-like strings, never an
            // enum, so hosts declare domain-specific proposal types.
            'type' => ['required', 'string', 'max:100', 'regex:/^[a-z0-9_]+$/'],
            // The validated-write backfill feeds raw database attributes
            // (a JSON-encoded string) on partial updates, so the rule
            // accepts both the logical array and its persisted encoding.
            'payload' => [
                'required',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    $valid = is_array($value)
                        || (is_string($value) && is_array(json_decode($value, true)));

                    if (! $valid) {
                        $fail("The {$attribute} field must be an array.");
                    }
                },
            ],
            'reason' => ['nullable', 'string', 'max:2000'],
            // 'sometimes': creation may omit it and the database default
            // ('pending') applies; updates backfill the current value.
            'status' => ['sometimes', 'string', Rule::in([
                self::STATUS_PENDING,
                self::STATUS_ACCEPTED,
                self::STATUS_REJECTED,
                self::STATUS_EXPIRED,
                self::STATUS_EXECUTING,
                self::STATUS_EXECUTED,
                self::STATUS_FAILED,
            ])],
            'expires_at' => ['nullable', 'date'],
            'decided_by' => ['sometimes', 'nullable', 'string', 'max:64'],
            'decided_at' => ['sometimes', 'nullable', 'date'],
            'decision_note' => ['sometimes', 'nullable', 'string', 'max:2000'],
            'original_payload' => [
                'sometimes',
                'nullable',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    if (is_null($value)) {
                        return;
                    }
                    if (is_array($value)) {
                        return;
                    }
                    if (is_string($value) && is_array(json_decode($value, true))) {
                        return;
                    }
                    $fail("The {$attribute} field must be an array or a valid JSON string.");
                },
            ],
            'source_type' => ['sometimes', 'nullable', 'string', 'max:255'],
            'source_id' => ['sometimes', 'nullable'],
            'ai_run_id' => ['sometimes', 'nullable', 'string', 'uuid'],
            'executed_at' => ['sometimes', 'nullable', 'date'],
            'execution_result' => [
                'sometimes',
                'nullable',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    if (is_null($value)) {
                        return;
                    }
                    if (is_array($value)) {
                        return;
                    }
                    if (is_string($value) && is_array(json_decode($value, true))) {
                        return;
                    }
                    $fail("The {$attribute} field must be an array or a valid JSON string.");
                },
            ],
            'execution_error' => ['sometimes', 'nullable', 'string', 'max:5000'],
        ];
    }

    /**
     * Validate a payload value against the model's payload rules plus any
     * extra rules provided by the caller (e.g. a ProposalHandler).
     *
     * @param  array<string, mixed>  $payload  The payload to validate.
     * @param  array<string, mixed>  $extraRules  Additional validation rules.
     *
     * @throws ValidationException When validation fails.
     */
    public function validatePayloadForWrite(array $payload, array $extraRules = []): void
    {
        $rules = array_merge([
            'payload' => [
                'required',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    $valid = is_array($value)
                        || (is_string($value) && is_array(json_decode($value, true)));

                    if (! $valid) {
                        $fail("The {$attribute} field must be an array.");
                    }
                },
            ],
        ], $extraRules);

        $validator = Validator::make(
            ['payload' => $payload],
            $rules,
        );

        if ($validator->fails()) {
            throw new ValidationException($validator);
        }
    }

    /**
     * Cross-field checks: the conversation, when supplied, must exist and
     * belong to the user receiving the proposal — a proposal can never be
     * attached to another user's conversation.
     *
     * @param  array<string, mixed>  $attributes
     */
    protected static function validateSecurity(array $attributes, ValidatorContract $validator, ?self $model = null): void
    {
        $conversationId = $attributes['conversation_id'] ?? null;

        if (! is_string($conversationId) || $conversationId === '') {
            return;
        }

        $conversation = AiConversation::query()->find($conversationId);

        if ($conversation === null) {
            $validator->errors()->add(
                'conversation_id',
                "The conversation [{$conversationId}] does not exist.",
            );

            return;
        }

        $ownerId = $attributes['user_id'] ?? $model->user_id ?? null;

        if ($ownerId !== null && (string) $conversation->user_id !== (string) $ownerId) {
            $validator->errors()->add(
                'conversation_id',
                'The conversation belongs to a different user.',
            );
        }
    }

    /**
     * The user who received the proposal (resolved via config('ai-agents.user_model')).
     *
     * @return BelongsTo<Model, $this>
     */
    public function user(): BelongsTo
    {
        /** @var class-string<Model> $userModel */
        $userModel = (string) config('ai-agents.user_model');

        return $this->belongsTo($userModel, 'user_id');
    }

    /**
     * The conversation that produced the proposal, if any.
     *
     * @return BelongsTo<AiConversation, $this>
     */
    public function conversation(): BelongsTo
    {
        return $this->belongsTo(AiConversation::class, 'conversation_id');
    }

    /**
     * The originating entity (morph), if any.
     *
     * @return MorphTo<Model, $this>
     */
    public function source(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * The AI run that generated this proposal, if any.
     *
     * @return BelongsTo<AiRun, $this>
     */
    public function aiRun(): BelongsTo
    {
        return $this->belongsTo(AiRun::class, 'ai_run_id');
    }

    /**
     * Whether the proposal is still waiting for a decision.
     */
    public function isPending(): bool
    {
        return $this->status === self::STATUS_PENDING;
    }

    /**
     * Whether the proposal's expiry has passed. A proposal without an
     * expiry never expires.
     */
    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }

    /**
     * Mark the proposal as accepted.
     *
     * Always fires `ActionProposalAccepted` when the transition succeeds
     * ($affected === 1), regardless of whether $deciderId is null.
     *
     * @param  int|string|null  $deciderId  The id of the user who accepted.
     * @param  array<string, mixed>|null  $amendedPayload  An amended payload.
     * @param  string|null  $note  Decision note.
     */
    public function accept(int|string|null $deciderId = null, ?array $amendedPayload = null, ?string $note = null): bool
    {
        $now = Carbon::now();
        $updateData = [
            'status' => self::STATUS_ACCEPTED,
            'decided_at' => $now,
        ];

        if ($deciderId !== null) {
            $updateData['decided_by'] = (string) $deciderId;
        }

        if ($note !== null) {
            $updateData['decision_note'] = $note;
        }

        if ($amendedPayload !== null) {
            // Copy current payload to original_payload in the same UPDATE.
            $updateData['original_payload'] = $this->payload;
            $updateData['payload'] = $amendedPayload;
        } else {
            // Always store original for traceability.
            $updateData['original_payload'] = $this->payload;
        }

        $query = static::query()
            ->where('id', $this->id)
            ->where('status', self::STATUS_PENDING)
            ->where(function ($q) use ($now) {
                $q->whereNull('expires_at')
                    ->orWhere('expires_at', '>', $now);
            });

        $affected = $query->update($updateData);

        if ($affected === 1) {
            $this->refresh();
            event(new ActionProposalAccepted($this, $deciderId));

            return true;
        }

        return false;
    }

    /**
     * Mark the proposal as rejected.
     *
     * Always fires `ActionProposalRejected` when the transition succeeds
     * ($affected === 1), regardless of whether $deciderId is null.
     *
     * @param  int|string|null  $deciderId  The id of the user who rejected.
     * @param  string|null  $note  Rejection note.
     */
    public function reject(int|string|null $deciderId = null, ?string $note = null): bool
    {
        $updateData = [
            'status' => self::STATUS_REJECTED,
            'decided_at' => Carbon::now(),
        ];

        if ($deciderId !== null) {
            $updateData['decided_by'] = (string) $deciderId;
        }

        if ($note !== null) {
            $updateData['decision_note'] = $note;
        }

        $query = static::query()
            ->where('id', $this->id)
            ->where('status', self::STATUS_PENDING)
            ->where(function ($q) {
                $q->whereNull('expires_at')
                    ->orWhere('expires_at', '>', Carbon::now());
            });

        $affected = $query->update($updateData);

        if ($affected === 1) {
            $this->refresh();
            event(new ActionProposalRejected($this, $deciderId));

            return true;
        }

        return false;
    }

    /**
     * Mark the proposal as executing (accepted → executing).
     *
     * @return bool True if the transition succeeded.
     */
    public function markExecuting(): bool
    {
        $query = static::query()
            ->where('id', $this->id)
            ->where('status', self::STATUS_ACCEPTED);

        $affected = $query->update([
            'status' => self::STATUS_EXECUTING,
        ]);

        if ($affected === 1) {
            $this->refresh();

            return true;
        }

        return false;
    }

    /**
     * Mark the proposal as executed (executing → executed).
     *
     * @param  array<string, mixed>  $result  The serialisable execution result.
     * @return bool True if the transition succeeded.
     */
    public function markExecuted(array $result): bool
    {
        $query = static::query()
            ->where('id', $this->id)
            ->where('status', self::STATUS_EXECUTING);

        $affected = $query->update([
            'status' => self::STATUS_EXECUTED,
            'execution_result' => $result,
            'executed_at' => Carbon::now(),
        ]);

        if ($affected === 1) {
            $this->refresh();

            event(new ActionProposalExecuted($this, $result));

            return true;
        }

        return false;
    }

    /**
     * Mark the proposal as failed (executing|accepted → failed).
     *
     * Including 'accepted' catches failures that occur while dispatching
     * the execution job.
     *
     * @param  string  $error  The error message.
     * @return bool True if the transition succeeded.
     */
    public function markFailed(string $error): bool
    {
        $query = static::query()
            ->where('id', $this->id)
            ->whereIn('status', [self::STATUS_EXECUTING, self::STATUS_ACCEPTED]);

        $affected = $query->update([
            'status' => self::STATUS_FAILED,
            'execution_error' => $error,
            'executed_at' => Carbon::now(),
        ]);

        if ($affected === 1) {
            $this->refresh();

            event(new ActionProposalFailed($this, $error));

            return true;
        }

        return false;
    }

    /**
     * Mark every stale pending proposal (expiry in the past) as expired.
     *
     * Iterates in batches, fires an event for each expired proposal.
     *
     * Schedule it (e.g. every five minutes) so pending proposals with an
     * expiry cannot be accepted long after their expiry silently.
     *
     * @return int The number of proposals marked expired.
     */
    public static function expireStale(): int
    {
        $count = 0;
        $now = Carbon::now();

        static::query()
            ->where('status', self::STATUS_PENDING)
            ->whereNotNull('expires_at')
            ->where('expires_at', '<', $now)
            ->chunkById(100, function (Collection $proposals) use (&$count, $now): void {
                foreach ($proposals as $proposal) {
                    $affected = static::query()
                        ->where('id', $proposal->id)
                        ->where('status', self::STATUS_PENDING)
                        ->where('expires_at', '<', $now)
                        ->update(['status' => self::STATUS_EXPIRED]);

                    if ($affected === 1) {
                        $proposal->refresh();
                        event(new ActionProposalExpired($proposal));
                        $count++;
                    }
                }
            });

        return $count;
    }

    /**
     * Scope to pending proposals of a specific source.
     *
     * @param  Builder<static>  $query
     * @param  Model  $source  The source model to filter by.
     * @return Builder<static>
     */
    public function scopeForSource(Builder $query, Model $source): Builder
    {
        return $query
            ->where('source_type', $source->getMorphClass())
            ->where('source_id', $source->getKey());
    }

    /**
     * Scope to proposals awaiting decision by a specific user.
     *
     * Delegates to the AuthorizesProposalDecisions resolver bound in the
     * container so custom authorizers can extend the scope beyond owner-only.
     *
     * @param  Builder<static>  $query
     * @param  int|string  $userId  The user id.
     * @return Builder<static>
     */
    public function scopeAwaitingDecisionBy(Builder $query, int|string $userId): Builder
    {
        // Explicit where() instead of the dynamic `pending()` scope keeps the
        // builder statically typed (PHPStan cannot resolve dynamic scopes).
        // The authorizer contract types the builder against AiActionProposal
        // (Builder's template is not covariant), so re-annotate before delegating.
        /** @var Builder<AiActionProposal> $pending */
        $pending = $query->where('status', self::STATUS_PENDING);

        try {
            $authorizer = app(AuthorizesProposalDecisions::class);

            /** @var Builder<static> $scoped */
            $scoped = $authorizer->applyDecisionScope($pending, $userId);

            return $scoped;
        } catch (\Throwable) {
            // Container cannot resolve the authorizer (e.g. tests without app
            // bootstrapped); fall back to owner-only.
            /** @var Builder<static> $fallback */
            $fallback = $pending->where('user_id', $userId);

            return $fallback;
        }
    }

    /**
     * Scope to the proposals of one user.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeForUser(Builder $query, int|string $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Normalise source and ai_run_id attributes before validated write.
     *
     * Accepts a 'source' key holding an Eloquent Model (resolved to
     * source_type/source_id) and/or an 'ai_run_id' string.
     *
     * @param  array<string, mixed>  $attributes
     * @param  Model|null  $source  The originating entity.
     * @param  string|null  $aiRunId  The AI run UUID.
     * @return array<string, mixed>
     */
    protected static function normalizeSourceAndRun(array $attributes, ?Model $source = null, ?string $aiRunId = null): array
    {
        if ($source !== null) {
            $attributes['source_type'] = $source->getMorphClass();
            $attributes['source_id'] = $source->getKey();
        }

        if ($aiRunId !== null) {
            $attributes['ai_run_id'] = $aiRunId;
        }

        return $attributes;
    }

    /**
     * Validate the attributes, resolve source/ai_run_id, and create a record.
     *
     * @param  array<string, mixed>  $attributes  The attributes to validate and insert.
     * @param  Model|null  $source  The originating entity (resolved to source_type/source_id).
     * @param  string|null  $aiRunId  The AI run UUID (stored as ai_run_id).
     * @return static The created model instance.
     *
     * @throws ValidationException When validation fails.
     */
    public static function createValidatedWithSource(array $attributes, ?Model $source = null, ?string $aiRunId = null): static
    {
        $attributes = static::resolveScope($attributes);
        $attributes = static::normalizeSourceAndRun($attributes, $source, $aiRunId);
        static::validateAttributes($attributes);

        /** @var static $model */
        $model = static::create($attributes);

        // Re-hydrate so the returned instance reflects the persisted row.
        $model->refresh();

        static::applyDerivedAttributes($model, $attributes);

        // NOTE: ActionProposalCreated is fired ONLY by the static::created() hook
        // below to guarantee exactly one event per creation path.

        return $model;
    }

    /**
     * Boot the model: fire ActionProposalCreated on every create path
     * (create, createValidated, createValidatedWithSource) without
     * duplicating the event already fired in createValidatedWithSource.
     */
    protected static function booted(): void
    {
        static::created(function (self $proposal): void {
            event(new ActionProposalCreated($proposal));
        });
    }
}
