<?php

declare(strict_types=1);

namespace HomeSide\AiAgents\Models;

use HomeSide\AiAgents\Models\Concerns\ValidatesOnWrite;
use HomeSide\AiAgents\Tenancy\BelongsToTenant;
use Illuminate\Contracts\Validation\Validator as ValidatorContract;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use Illuminate\Validation\Rule;

/**
 * A proposed action generated by an agent that awaits user acceptance.
 *
 * Human-in-the-loop pattern: agents never mutate host data directly. A tool
 * (typically built from stubs/ActionProposalTool.php.stub) creates a pending
 * proposal; the user accepts or rejects it through the host's own action,
 * which dispatches to domain handlers. The package standardises persistence,
 * validation, lifecycle and querying — executing the proposed action always
 * remains host-side because proposal types and handlers are domain-specific.
 *
 * @property string $id UUID primary key.
 * @property int|string $user_id The id of the user who received the proposal.
 * @property int|string|null $household_id The tenant id (column name configurable), if any.
 * @property string|null $conversation_id The id of the conversation that produced the proposal, if any.
 * @property string $type Host-defined proposal type (e.g. 'add_shopping_items').
 * @property array<string, mixed> $payload The action payload.
 * @property string|null $reason Human-readable explanation shown to the user.
 * @property string $status pending|accepted|rejected|expired.
 * @property Carbon|null $expires_at When the proposal expires, if any.
 * @property Carbon|null $created_at The timestamp when the proposal was created.
 * @property Carbon|null $updated_at The timestamp when the proposal was last updated.
 *
 * Relationships:
 * @property Model|null $user The user who received the proposal (resolved via config).
 * @property AiConversation|null $conversation The conversation that produced the proposal.
 */
class AiActionProposal extends Model
{
    use BelongsToTenant, HasUuids, ValidatesOnWrite;

    public const STATUS_PENDING = 'pending';

    public const STATUS_ACCEPTED = 'accepted';

    public const STATUS_REJECTED = 'rejected';

    public const STATUS_EXPIRED = 'expired';

    protected $fillable = [
        'user_id',
        'conversation_id',
        'type',
        'payload',
        'reason',
        'status',
        'expires_at',
    ];

    /**
     * Get the attribute casts for the model.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'payload' => 'array',
            'expires_at' => 'datetime',
        ];
    }

    /**
     * Validation rules for validated writes.
     *
     * @return array<string, mixed>
     */
    protected static function rules(): array
    {
        return [
            'user_id' => ['required'],
            'conversation_id' => ['nullable', 'string', 'max:64'],
            // Host-defined types: lowercase slug-like strings, never an
            // enum, so hosts declare domain-specific proposal types.
            'type' => ['required', 'string', 'max:100', 'regex:/^[a-z0-9_]+$/'],
            // The validated-write backfill feeds raw database attributes
            // (a JSON-encoded string) on partial updates, so the rule
            // accepts both the logical array and its persisted encoding.
            'payload' => [
                'required',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    $valid = is_array($value)
                        || (is_string($value) && is_array(json_decode($value, true)));

                    if (! $valid) {
                        $fail("The {$attribute} field must be an array.");
                    }
                },
            ],
            'reason' => ['nullable', 'string', 'max:2000'],
            // 'sometimes': creation may omit it and the database default
            // ('pending') applies; updates backfill the current value.
            'status' => ['sometimes', 'string', Rule::in([
                self::STATUS_PENDING,
                self::STATUS_ACCEPTED,
                self::STATUS_REJECTED,
                self::STATUS_EXPIRED,
            ])],
            'expires_at' => ['nullable', 'date'],
        ];
    }

    /**
     * Cross-field checks: the conversation, when supplied, must exist and
     * belong to the user receiving the proposal — a proposal can never be
     * attached to another user's conversation.
     *
     * @param  array<string, mixed>  $attributes
     */
    protected static function validateSecurity(array $attributes, ValidatorContract $validator, ?self $model = null): void
    {
        $conversationId = $attributes['conversation_id'] ?? null;

        if (! is_string($conversationId) || $conversationId === '') {
            return;
        }

        $conversation = AiConversation::query()->find($conversationId);

        if ($conversation === null) {
            $validator->errors()->add(
                'conversation_id',
                "The conversation [{$conversationId}] does not exist.",
            );

            return;
        }

        $ownerId = $attributes['user_id'] ?? $model->user_id ?? null;

        if ($ownerId !== null && (string) $conversation->user_id !== (string) $ownerId) {
            $validator->errors()->add(
                'conversation_id',
                'The conversation belongs to a different user.',
            );
        }
    }

    /**
     * The user who received the proposal (resolved via config('ai-agents.user_model')).
     *
     * @return BelongsTo<Model, $this>
     */
    public function user(): BelongsTo
    {
        /** @var class-string<Model> $userModel */
        $userModel = (string) config('ai-agents.user_model');

        return $this->belongsTo($userModel, 'user_id');
    }

    /**
     * The conversation that produced the proposal, if any.
     *
     * @return BelongsTo<AiConversation, $this>
     */
    public function conversation(): BelongsTo
    {
        return $this->belongsTo(AiConversation::class, 'conversation_id');
    }

    /**
     * Whether the proposal is still waiting for a decision.
     */
    public function isPending(): bool
    {
        return $this->status === self::STATUS_PENDING;
    }

    /**
     * Whether the proposal's expiry has passed. A proposal without an
     * expiry never expires.
     */
    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }

    /**
     * Mark the proposal as accepted.
     */
    public function accept(): bool
    {
        return $this->update(['status' => self::STATUS_ACCEPTED]);
    }

    /**
     * Mark the proposal as rejected.
     */
    public function reject(): bool
    {
        return $this->update(['status' => self::STATUS_REJECTED]);
    }

    /**
     * Mark every stale pending proposal (expiry in the past) as expired.
     *
     * Schedule it (e.g. daily) so pending proposals with an expiry cannot be
     * accepted long after their expiry silently.
     *
     * @return int The number of proposals marked expired.
     */
    public static function expireStale(): int
    {
        return static::query()
            ->where('status', self::STATUS_PENDING)
            ->whereNotNull('expires_at')
            ->where('expires_at', '<', Carbon::now())
            ->update(['status' => self::STATUS_EXPIRED]);
    }

    /**
     * Scope to pending proposals.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopePending(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_PENDING);
    }

    /**
     * Scope to the proposals of one user.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeForUser(Builder $query, int|string $userId): Builder
    {
        return $query->where('user_id', $userId);
    }
}
