<?php

declare(strict_types=1);

namespace HomeSide\AiAgents\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * A single execution attempt of an AI run, used to record retries.
 *
 * @property string $id The unique identifier for the execution attempt (UUID).
 * @property string $ai_run_id The id of the AI run the attempt belongs to.
 * @property int $attempt_order The order of the attempt within the run.
 * @property string|null $provider_id The id of the AI provider used for the attempt.
 * @property string|null $model_name The name of the model used for the attempt.
 * @property string $status The status of the attempt.
 * @property string|null $error_code The error code returned by the provider, if any.
 * @property int|null $input_tokens The number of input tokens used by the attempt.
 * @property int|null $output_tokens The number of output tokens generated by the attempt.
 * @property int|null $duration_ms The duration of the attempt in milliseconds.
 * @property Carbon|null $created_at The timestamp when the attempt was created.
 * @property Carbon|null $updated_at The timestamp when the attempt was last updated.
 *
 * Relationships:
 * @property AiRun|null $run The AI run the attempt belongs to.
 */
class AiExecutionAttempt extends Model
{
    use HasUuids;

    protected $fillable = [
        'ai_run_id',
        'attempt_order',
        'provider_id',
        'model_name',
        'status',
        'error_code',
        'input_tokens',
        'output_tokens',
        'duration_ms',
    ];

    /**
     * Get the attribute casts for the model.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'attempt_order' => 'integer',
            'input_tokens' => 'integer',
            'output_tokens' => 'integer',
            'duration_ms' => 'integer',
        ];
    }

    /** @return BelongsTo<AiRun, $this> */
    public function run(): BelongsTo
    {
        return $this->belongsTo(AiRun::class, 'ai_run_id');
    }
}
