<?php

declare(strict_types=1);

namespace HomeSide\AiAgents\Models;

use HomeSide\AiAgents\Models\Casts\RunContentCast;
use HomeSide\AiAgents\Tenancy\BelongsToTenant;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;

/**
 * A single AI execution run, recording usage, status and the conversation it
 * belongs to.
 *
 * @property string $id The unique identifier for the run (UUID).
 * @property string $user_id The id of the user who triggered the run.
 * @property string|null $household_id The tenant id (column name configurable), if any.
 * @property string|null $conversation_id The id of the AI conversation the run belongs to, if any.
 * @property string $agent The agent that executed the run.
 * @property int $agent_version The version of the agent that executed the run.
 * @property string|null $provider_id The id of the AI provider used for the run, if any.
 * @property string|null $provider_name The name of the AI provider used for the run, if any.
 * @property string|null $model_name The name of the model used for the run, if any.
 * @property int|null $input_tokens The number of input tokens used by the run.
 * @property int|null $output_tokens The number of output tokens generated by the run.
 * @property int|null $cached_tokens The number of cached tokens used by the run.
 * @property string|null $estimated_cost The estimated USD cost of the run (snapshot at result time).
 * @property int|null $duration_ms The duration of the run in milliseconds.
 * @property string $status The status of the run.
 * @property string|null $error_code The error code returned by the provider, if any.
 * @property string|null $user_message The user message of the run, if any (decrypted transparently when content_mode is encrypted).
 * @property string|null $reply The reply generated by the agent, if any (decrypted transparently when content_mode is encrypted).
 * @property string $content_mode How the content is stored (ContentMode value: encrypted|plain|redacted|none).
 * @property Carbon|null $content_granted_at When support access was granted.
 * @property int|string|null $content_granted_by The user who granted support access.
 * @property string|null $content_grant_reference The external ticket reference of the grant.
 * @property Carbon|null $content_grant_expires_at When the support grant expires (null = no expiry).
 * @property array<string, mixed>|null $metadata Additional run metadata.
 * @property Carbon|null $created_at The timestamp when the run was created.
 * @property Carbon|null $updated_at The timestamp when the run was last updated.
 *
 * Relationships:
 * @property Model|null $user The user who triggered the run (resolved via config).
 * @property Collection<int, AiExecutionAttempt> $attempts The execution attempts of the run.
 * @property Collection<int, AiToolCall> $toolCalls The tool calls made during the run.
 */
class AiRun extends Model
{
    use BelongsToTenant, HasUuids;

    protected $fillable = [
        'user_id',
        'conversation_id',
        'agent',
        'agent_version',
        'provider_id',
        'provider_name',
        'model_name',
        'input_tokens',
        'output_tokens',
        'cached_tokens',
        'estimated_cost',
        'duration_ms',
        'status',
        'error_code',
        'user_message',
        'reply',
        'content_mode',
        'content_granted_at',
        'content_granted_by',
        'content_grant_reference',
        'content_grant_expires_at',
        'metadata',
    ];

    /**
     * Get the attribute casts for the model.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'input_tokens' => 'integer',
            'output_tokens' => 'integer',
            'cached_tokens' => 'integer',
            'estimated_cost' => 'decimal:6',
            'duration_ms' => 'integer',
            'agent_version' => 'integer',
            'metadata' => 'array',
            'user_message' => RunContentCast::class,
            'reply' => RunContentCast::class,
            'content_granted_at' => 'datetime',
            'content_grant_expires_at' => 'datetime',
        ];
    }

    /**
     * Whether this run's content is currently readable by support: a grant
     * exists, has a reference, and has not expired.
     */
    public function hasActiveSupportGrant(): bool
    {
        return $this->content_granted_at !== null
            && $this->content_grant_reference !== null
            && ($this->content_grant_expires_at === null
                || $this->content_grant_expires_at->isFuture());
    }

    /**
     * Clear the support grant from this run (revoke).
     */
    public function clearSupportGrant(): void
    {
        $this->forceFill([
            'content_granted_at' => null,
            'content_granted_by' => null,
            'content_grant_reference' => null,
            'content_grant_expires_at' => null,
        ])->save();
    }

    /**
     * The user who triggered the run (resolved via config('ai-agents.user_model')).
     *
     * @return BelongsTo<Model, $this>
     */
    public function user(): BelongsTo
    {
        /** @var class-string<Model> $userModel */
        $userModel = (string) config('ai-agents.user_model');

        return $this->belongsTo($userModel, 'user_id');
    }

    /** @return BelongsTo<AiConversation, $this> */
    public function conversation(): BelongsTo
    {
        return $this->belongsTo(AiConversation::class, 'conversation_id');
    }

    /** @return HasMany<AiExecutionAttempt, $this> */
    public function attempts(): HasMany
    {
        return $this->hasMany(AiExecutionAttempt::class);
    }

    /** @return HasMany<AiToolCall, $this> */
    public function toolCalls(): HasMany
    {
        return $this->hasMany(AiToolCall::class);
    }

    /**
     * Query scope: restrict runs to one user's history.
     *
     * @param  Builder<AiRun>  $query  The builder being scoped.
     * @param  int|string  $userId  Host user identifier (integer or UUID).
     * @return Builder<AiRun> Runs where user_id matches exactly.
     */
    public function scopeForUser(Builder $query, int|string $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Query scope: restrict runs to a single agent key.
     *
     * @param  Builder<AiRun>  $query  The builder being scoped.
     * @param  string  $agent  The canonical agent key (e.g. 'recipes.recipe_generator').
     * @return Builder<AiRun> Runs where agent matches exactly.
     */
    public function scopeForAgent(Builder $query, string $agent): Builder
    {
        return $query->where('agent', $agent);
    }
}
